package net.projecteuler;


import java.util.*;

import javax.swing.JOptionPane;
/**
 * 
 * @author Brian
 * Project Euler Problem #2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 *
 */
public class EvenFibNum {
	private static long startTime = System.currentTimeMillis();
	public static void main(String[] args) {
		ArrayList<Integer> array = new ArrayList<Integer>() ;
		array.add(1);
		array.add(1);
		long sum = 0;
		int i=2;
		while(true){
			if(sum>4000000)
				break;
			array.add(array.get(i-1)+array.get(i-2));
			if(array.get(i)%2==0){
				sum+=array.get(i);
			}
			i++;
		}
		System.out.println(sum);
		long endTime = System.currentTimeMillis();
		System.out.println("Time completion: " + (endTime-startTime));
	}//main
}//EvenFibNum Class
