=begin
Author: Brian
Project Euler Problem #2
Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.

=end

fibonacci = Hash.new

puts "the sum of the even fibonacci numbers that do not exceed 4000000 are..."

fibonacci[1]=1
fibonacci[2]=2
i =3
sum=2
#iterate through 3...nth and store the previous 2 terms and then add the sum of the fibonacci #
while true
	fibonacci[i]=fibonacci[i-1]+fibonacci[i-2]
	if fibonacci[i]%2 ==0
		sum+=fibonacci[i]
	end
	break if fibonacci[i]>4000000
	i+=1
end

puts sum
